/**
 * Delta Engine surface — embeds the agent-based market-simulation PoC visualisation.
 *
 * The PoC itself lives under `/throwaway` and the regime boundary forbids `/prod` (this web app)
 * from importing `/throwaway`. This surface therefore embeds the pre-generated, self-contained
 * visualisation as a STATIC ASSET via an <iframe> — it imports no `/throwaway` code. The asset is
 * `public/delta-engine.html`, (re)generated by
 * `pnpm exec tsx throwaway/delta-engine/src/gen-asset.ts`.
 *
 * R&D / Throwaway: this is an exploratory simulation, disjoint from ROSE P0.
 */
const ASSET_SRC = `${import.meta.env.BASE_URL}delta-engine.html`;

export function DeltaEngineSurface(): React.JSX.Element {
  return (
    <div className="flex flex-col gap-3">
      <div className="flex items-center gap-3">
        <h1 className="font-display text-lg font-semibold">Delta Engine</h1>
        <span className="rounded-full border border-border px-2 py-0.5 text-xs text-muted-foreground">
          R&amp;D · Throwaway PoC
        </span>
      </div>
      <p className="max-w-3xl text-sm text-muted-foreground">
        A contrarian, multi-scale directional-change (intrinsic-time) trading model from
        Glattfelder/Houweling/Olsen (2025) — one agent per δ threshold decomposes the price into
        directional-change events, fits support/resistance lines, and fades breakouts; the net
        exposure oscillates between +u and −u and is decoupled from PnL (no take-profit /
        stop-loss). A volatility-feedback loop temporarily silences agents whose activity falls out
        of sync. Disjoint from ROSE P0. Embedded read-only visualisation of a sample run.
      </p>
      <iframe
        title="Delta Engine PoC visualisation"
        src={ASSET_SRC}
        className="h-[78vh] w-full rounded-lg border border-border bg-background"
      />
    </div>
  );
}
