/**
 * Alpha Engine surface — embeds the agent-based market-simulation PoC visualisation.
 *
 * The PoC itself lives under `/throwaway` and the regime boundary forbids `/prod` (this web app)
 * from importing `/throwaway`. This surface therefore embeds the pre-generated, self-contained
 * visualisation as a STATIC ASSET via an <iframe> — it imports no `/throwaway` code. The asset is
 * `public/alpha-engine.html`, (re)generated by
 * `pnpm exec tsx throwaway/alpha-engine/src/gen-asset.ts`.
 *
 * R&D / Throwaway: this is an exploratory simulation, disjoint from ROSE P0.
 */
const ASSET_SRC = `${import.meta.env.BASE_URL}alpha-engine.html`;

export function AlphaEngineSurface(): React.JSX.Element {
  return (
    <div className="flex flex-col gap-3">
      <div className="flex items-center gap-3">
        <h1 className="font-display text-lg font-semibold">Alpha Engine</h1>
        <span className="rounded-full border border-border px-2 py-0.5 text-xs text-muted-foreground">
          R&amp;D · Throwaway PoC
        </span>
      </div>
      <p className="max-w-3xl text-sm text-muted-foreground">
        Closed agent-based market simulation — two populations of long/short agents whose trades
        fire on accumulated carry pressure, cleared each tick by a Dutch auction into an endogenous
        price. Internal market only; disjoint from ROSE P0. Embedded read-only visualisation of a
        sample run.
      </p>
      <iframe
        title="Alpha Engine PoC visualisation"
        src={ASSET_SRC}
        className="h-[78vh] w-full rounded-lg border border-border bg-background"
      />
    </div>
  );
}
