// @rose/rule-spec — codegen: materialize the GENERATED on-chain compliance Solidity library
// (Story 4.5).
//
// `generateOnChainSolidityConfig` emits the source of `library GeneratedComplianceConfig`, a
// committed-to-`prod/contracts/src/generated/` library DERIVED from `ruleSpecV1`. It is the
// on-chain counterpart of the off-chain `flow_permissions` seed: the previously hand-pinned
// `ClaimTopics.ONCHAINID_KYC` (Story 4.1) now references the GENERATED constant here, and the
// `ClaimTopicsRegistry` is seeded via the generated `seedClaimTopics` helper. The numeric topic id
// is `uint256(keccak256("<LABEL>"))` — computed by the EVM (the authority), with the LABEL injected
// from the single-source rule-spec. Output is deterministic; a Vitest drift guard fails on any
// hand-edit.
import type { RuleSpec } from '../spec/rule-spec-schema.js';

const GENERATOR_ID = '@rose/rule-spec/codegen/generate-on-chain-solidity';
const IDENTIFIER_SAFE = /^[A-Z][A-Z0-9_]*$/;

function solBool(value: boolean): string {
  return value ? 'true' : 'false';
}

/**
 * Emit the `GeneratedComplianceConfig` Solidity library source from a validated rule spec.
 * Deterministic: same spec ⇒ byte-identical source. The file is committed under
 * `prod/contracts/src/generated/` and is `[fmt] ignore`d (the emitter — not `forge fmt` — owns its
 * exact bytes; the Vitest drift guard enforces it).
 */
export function generateOnChainSolidityConfig(spec: RuleSpec): string {
  const labels = spec.eligibility.requiredClaimTopics;
  for (const label of labels) {
    if (!IDENTIFIER_SAFE.test(label)) {
      throw new Error(
        `claim-topic label "${label}" is not EVM-identifier-safe (must match ${IDENTIFIER_SAFE.source})`,
      );
    }
  }

  const topicConstants = labels
    .map(
      (label) =>
        `    /// @notice Required eligibility claim topic \`${label}\` (rule-spec single source).\n` +
        `    uint256 internal constant ${label} = uint256(keccak256("${label}"));`,
    )
    .join('\n\n');

  const topicAssignments = labels.map((label, i) => `        topics[${i}] = ${label};`).join('\n');

  return `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

// AUTOGENERATED FROM @rose/rule-spec \`ruleSpecV1\` BY ${GENERATOR_ID} — DO NOT EDIT.
// Regenerate with \`pnpm --filter @rose/rule-spec generate\`. A Vitest drift guard
// (generated-on-chain-artifact-drift.test.ts) fails if this file is hand-edited.

import {ClaimTopicsRegistry} from "../identity/ClaimTopicsRegistry.sol";

/// @title GeneratedComplianceConfig — on-chain compliance config derived from the rule-spec
/// @notice The single source of truth is \`prod/packages/rule-spec/src/spec/rule-spec.v1.ts\`.
///         This library materializes the on-chain projection of that spec: the required
///         eligibility claim-topic ids (\`uint256(keccak256(label))\`), the allowlist requirement,
///         and the pair-coupling flags. Story 4.5 (FR-19, §8 Q5, SM-4).
library GeneratedComplianceConfig {
${topicConstants}

    /// @notice Whether eligibility requires the curated allowlist (the on-chain \`IdentityRegistry\`).
    bool internal constant REQUIRE_ALLOWLIST = ${solBool(spec.eligibility.requireAllowlist)};

    /// @notice Whether paired mint/burn must be atomic (enforced by \`CoupledPair\`, Story 4.3).
    bool internal constant ATOMIC_PAIRED_MINT_BURN = ${solBool(spec.pairCoupling.atomicPairedMintBurn)};

    /// @notice Whether a single-leg mint/burn is forbidden (enforced by \`CoupledPair\`, Story 4.3).
    bool internal constant SINGLE_LEG_FORBIDDEN = ${solBool(spec.pairCoupling.singleLegForbidden)};

    /// @notice The required eligibility claim topics, in rule-spec order.
    function requiredClaimTopics() internal pure returns (uint256[] memory topics) {
        topics = new uint256[](${labels.length});
${topicAssignments}
    }

    /// @notice Seed a \`ClaimTopicsRegistry\` with the generated required topics. The caller MUST be
    ///         the registry owner (\`addClaimTopic\` is \`onlyOwner\`). This is the reusable
    ///         "amorçage" primitive the Story 4.6 deploy script will call.
    function seedClaimTopics(ClaimTopicsRegistry registry) internal {
        uint256[] memory topics = requiredClaimTopics();
        for (uint256 i = 0; i < topics.length; i++) {
            registry.addClaimTopic(topics[i]);
        }
    }
}
`;
}
