// CoupledPair ABI subset — sourced from `prod/contracts/out/CoupledPair.sol/CoupledPair.json`
// (.abi), regenerated by `forge build`. Curated `as const` subset: the P0 watch set
// (`PairMinted`/`PairBurned`) plus `PairDeployed`, the paired-mint WRITE `mintPair` (Story 5.3, the
// saga `submit` for `PAIR_MINT`) and the paired-burn WRITE `burnPair` (Story 5.4, the saga `submit`
// for `PAIR_BURN`). MUST stay signature-identical to the on-chain contract; do NOT hand-edit
// signatures. `as const` enables viem's read/write/event-arg type inference
// (lTo/sTo/lFrom/sFrom: Address, amount: bigint, …).
export const coupledPairAbi = [
  {
    type: 'function',
    name: 'mintPair',
    inputs: [
      { name: 'lTo', type: 'address', internalType: 'address' },
      { name: 'sTo', type: 'address', internalType: 'address' },
      { name: 'amount', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'burnPair',
    inputs: [
      { name: 'lFrom', type: 'address', internalType: 'address' },
      { name: 'sFrom', type: 'address', internalType: 'address' },
      { name: 'amount', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'event',
    name: 'PairMinted',
    inputs: [
      { name: 'lTo', type: 'address', indexed: true, internalType: 'address' },
      { name: 'sTo', type: 'address', indexed: true, internalType: 'address' },
      { name: 'amount', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'PairBurned',
    inputs: [
      { name: 'lFrom', type: 'address', indexed: true, internalType: 'address' },
      { name: 'sFrom', type: 'address', indexed: true, internalType: 'address' },
      { name: 'amount', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'PairDeployed',
    inputs: [
      { name: 'lToken', type: 'address', indexed: true, internalType: 'address' },
      { name: 'sToken', type: 'address', indexed: true, internalType: 'address' },
    ],
    anonymous: false,
  },
] as const;
